model {
  file: "model.sdf"
}
name: "Great_Dinos_Triceratops_Toy"
description: "Great Dinos Triceratops Toy\ntest"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "WowToyz"
}
annotations {
  key: "gtin"
  value: "783746025406"
}
annotations {
  key: "sku"
  value: "783746025406"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
