model {
  file: "model.sdf"
}
name: "Sapota_Threshold_4_Ceramic_Round_Planter_Red"
description: "Sapota Threshold 4\" Ceramic Round Planter Red"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Sapota"
}
annotations {
  key: "gtin"
  value: "00490841514994"
}
annotations {
  key: "sku"
  value: "00490841514994"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
